/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdio.h>
#include <stdbool.h>
#include "stm32f407xx.h"
#include "reg_util.h"
#include "bsp_lcd.h"


extern lcd_context_t g_lcd_context;
extern const uint8_t iniyaal[240*308*2];
extern const uint8_t pavithiran[240*308*2];

void SystemClockSetup();
void LCD_display_portrait_image_whole_screen(const uint8_t *image, size_t size_in_bytes);
void LCD_display_portrait_image_in_landscape_mode(const uint8_t *image, const uint16_t img_w, const uint16_t img_h );
void LCD_display_portrait_bottom_up(const uint8_t *image, const uint16_t img_w, const uint16_t img_h);
void LCD_display_portrait_top_bottom(const uint8_t *image, const uint16_t img_w, const uint16_t img_h);


void delay()
{
	unsigned int i;
	for(i = 0; i < 2000000; i++);
	for(i = 0; i < 2000000; i++);
	for(i = 0; i < 2000000; i++);
}


int main(void)
{
	unsigned int i;
	bool slide_from_top = true; // true - from top, false - from bottom

	SystemClockSetup();

	LCD_Init();

	g_lcd_context.ori.orientation = PORTRAIT;

	LCD_set_orientation(&g_lcd_context);

	for(i = 0; i < 2000000; i++);


	GPIOD->MODER |= GPIO_MODER_MODER12_0; // Green LED, set pin 12 as output
	GPIOD->MODER |= GPIO_MODER_MODER13_0; // Orange LED, set pin 13 as output
	GPIOD->MODER |= GPIO_MODER_MODER14_0; // Red LED, set pin 14 as output
	GPIOD->MODER |= GPIO_MODER_MODER15_0; // Blue LED, set pin 15 as output

	LCD_set_background(&g_lcd_context, WHITE);


	LCD_display_portrait_image_whole_screen(iniyaal, sizeof(iniyaal));
	delay();
	g_lcd_context.ori.orientation = LANDSCAPE;
	LCD_set_orientation(&g_lcd_context);
	LCD_set_background(&g_lcd_context, WHITE);
	LCD_display_portrait_image_in_landscape_mode(iniyaal, 240, 308);
	delay();

	g_lcd_context.ori.orientation = PORTRAIT;
	LCD_set_orientation(&g_lcd_context);

    /* Loop forever */
	for(;;){

		// Turn on LEDs
		GPIOD->BSRR |= 1<<12; // Set the BSRR bit 12 to 1 to turn respective LED on
		GPIOD->BSRR |= 1<<13; // Set the BSRR bit 13 to 1 to turn respective LED on
		GPIOD->BSRR |= 1<<14; // Set the BSRR bit 14 to 1 to turn respective LED on
		GPIOD->BSRR |= 1<<15; // Set the BSRR bit 15 to 1 to turn respective LED on

		if(!slide_from_top)
			LCD_display_portrait_top_bottom(iniyaal, 240, 308);
		else
			LCD_display_portrait_bottom_up(iniyaal, 240, 308);

		delay();

		// Turn off LEDs
		GPIOD->BSRR |= 1<<(12+16); // Set the BSRR bit 12 + 16 to 1 to turn respective LED off
		GPIOD->BSRR |= 1<<(13+16); // Set the BSRR bit 13 + 16 to 1 to turn respective LED off
		GPIOD->BSRR |= 1<<(14+16); // Set the BSRR bit 14 + 16 to 1 to turn respective LED off
		GPIOD->BSRR |= 1<<(15+16); // Set the BSRR bit 15 + 16 to 1 to turn respective LED off

		if(!slide_from_top)
			LCD_display_portrait_top_bottom(pavithiran, 240, 308);
		else
			LCD_display_portrait_bottom_up(pavithiran, 240, 308);


		slide_from_top = !slide_from_top;

		delay();
	}
}

void SystemClockSetup(void)
{
	RCC_TypeDef *pRCC = RCC;
	FLASH_TypeDef *pFLASH = FLASH_ACR;
	PWR_TypeDef *pPWR = PWR;
	GPIO_TypeDef *pGPIOA = GPIOA;

	/*setting access control register to set 5 wait cycles.*/
	REG_SET_VAL(pFLASH->ACR,FLASH_ACR_LATENCY_5WS, FLASH_ACR_LATENCY_Msk, FLASH_ACR_LATENCY_Pos);

	/*Enabling the clock to access power control register*/
	REG_SET_BIT(pRCC->APB1ENR, RCC_APB1ENR_PWREN_Pos);

	/*setting VOS bit to 1 to achieve 168 MHZ frequency in PLL mode*/
	REG_SET_BIT(pPWR->CR, PWR_CR_VOS_Pos);

	/*Turn off PLL and make sure PLL is off*/
	REG_CLR_BIT(pRCC->CR, RCC_CR_PLLON_Pos);
	while (REG_READ_BIT(pRCC->CR, RCC_CR_PLLRDY_Pos));

	/*configure PLL registers to get 168MHZ max*/
	REG_SET_VAL(pRCC->PLLCFGR, 16U, RCC_PLLCFGR_PLLM_Msk, RCC_PLLCFGR_PLLM_Pos);  /*PLL_M*/
	REG_SET_VAL(pRCC->PLLCFGR, 336U, RCC_PLLCFGR_PLLN_Msk, RCC_PLLCFGR_PLLN_Pos);  /*PLL_N*/
	REG_SET_VAL(pRCC->PLLCFGR, 0U, RCC_PLLCFGR_PLLP_Msk, RCC_PLLCFGR_PLLP_Pos);  /*PLL_P*/

    /* configure AHB and APBx prescalers*/
	REG_SET_VAL(pRCC->CFGR, RCC_CFGR_HPRE_DIV1,  RCC_CFGR_HPRE_Msk,  RCC_CFGR_HPRE_Pos); /* HCLK 168MHZ no division*/
  	REG_SET_VAL(pRCC->CFGR, RCC_CFGR_PPRE1_DIV2, RCC_CFGR_PPRE2_Msk, RCC_CFGR_PPRE2_Pos);/* PCLK2 84MHZ HCLK/2*/
	REG_SET_VAL(pRCC->CFGR, RCC_CFGR_PPRE2_DIV4, RCC_CFGR_PPRE1_Msk, RCC_CFGR_PPRE1_Pos);/* PCLK1 42MHZ HCLK/4 */

	/*Turn on PLL and wait for the PLL to be ready*/
	REG_SET_BIT(pRCC->CR, RCC_CR_PLLON_Pos);
	while(!REG_READ_BIT(pRCC->CR,RCC_CR_PLLRDY_Pos));

	/*Set system clock source as PLL and wait for the configuration*/
	REG_SET_VAL(pRCC->CFGR, 0x2U, RCC_CFGR_SW_Msk, RCC_CFGR_SW_Pos);
	while((REG_READ_VAL(pRCC->CFGR, 0x03U, RCC_CFGR_SWS_Pos) != 0x02U));

	/***********This part is clock pll clock verification purposes**************/

	/* setting clock out on MCO1(PA8) pin to make sure 168MHZ clock is getting
	 * generated in PLL and system clock is 168MHZ*/
	REG_SET_VAL(pRCC->CFGR, 0x03U,  RCC_CFGR_MCO1_Msk,  RCC_CFGR_MCO1_Pos); /*MCO1 choose PLL as clock source*/
	REG_SET_VAL(pRCC->CFGR, 0x00U,  RCC_CFGR_MCO1PRE_Msk,  RCC_CFGR_MCO1PRE_Pos); /* Pre Scaler for MCO1. */

	REG_SET_BIT(pRCC->AHB1ENR, RCC_AHB1ENR_GPIOAEN_Pos);/*Enabling the clock to port A*/
	REG_SET_VAL(pGPIOA->MODER, 0x02U, GPIO_MODER_MODER8_Msk, GPIO_MODER_MODER8_Pos);/*GPIO pin 8 mode as Alternate Function*/
	REG_SET_VAL(pGPIOA->OSPEEDR, 0x03U, GPIO_OSPEEDR_OSPEED8_Msk, GPIO_OSPEEDR_OSPEED8_Pos);/*Set speed as high speed*/
	REG_SET_VAL(pGPIOA->PUPDR, 0x00U, GPIO_PUPDR_PUPD8_Msk, GPIO_PUPDR_PUPD8_Pos); /* Setting no pull up and no pull down*/
	REG_SET_VAL(pGPIOA->AFR[1], 0x00U, GPIO_AFRH_AFSEL8_Msk, GPIO_AFRH_AFSEL8_Pos);/*select AF0 as alternate function*/

	/***********This part is clock pll clock verification purposes**************/

	/*Enabling the clock to port D*/
	REG_SET_BIT(pRCC->AHB1ENR, RCC_AHB1ENR_GPIODEN_Pos);
}

void LCD_display_portrait_top_bottom(const uint8_t *image, const uint16_t img_w, const uint16_t img_h)
{
	uint8_t line_step_size = 1;
	uint32_t iterations = img_h / line_step_size;
	uint32_t remainder = img_h % line_step_size;
	uint32_t image_size_in_pixels = 0;
	uint32_t i = 0, temp = 0;

	for(i = 1; i <= (iterations + remainder); i++)
	{
		uint32_t height = (line_step_size *i);

		if(i >= iterations)
		{
			temp = (i == iterations) ? (i) : (temp);
			height = ((i-temp) + (temp * line_step_size));
		}
		g_lcd_context.area.x1.whole = 0;
		g_lcd_context.area.y1.whole = 0;
		g_lcd_context.area.x2.whole = PORTRAIT_ACTIVE_WIDTH - 1;
		g_lcd_context.area.y2.whole = height - 1;

		image_size_in_pixels = ( height * PORTRAIT_ACTIVE_WIDTH);
		uint32_t img_offset = ((img_w * img_h * 2) - (height * PORTRAIT_ACTIVE_WIDTH * 2));

		uint8_t *buff_offset = (uint8_t *)(image + img_offset);
		LCD_display_image(buff_offset, image_size_in_pixels, (const lcd_context_t *)&g_lcd_context);
	}
}

void LCD_display_portrait_bottom_up(const uint8_t *image, const uint16_t img_w, const uint16_t img_h)
{
	uint16_t step = 200;
	uint8_t height_step_size = PORTRAIT_ACTIVE_HEIGHT/step;
	uint8_t remainder_10s = PORTRAIT_ACTIVE_HEIGHT%step;
	uint32_t image_size_in_pixels = 0;
	uint16_t i;
	g_lcd_context.ori.orientation = PORTRAIT;

	for(i = 1; i <= step; i++)
	{
		g_lcd_context.area.x1.whole = 0;
		g_lcd_context.area.y1.whole = (PORTRAIT_ACTIVE_HEIGHT - (height_step_size * i)-1);
		g_lcd_context.area.x2.whole = PORTRAIT_ACTIVE_WIDTH - 1;
		g_lcd_context.area.y2.whole = PORTRAIT_ACTIVE_HEIGHT - 1;
		image_size_in_pixels = height_step_size * i * img_w;

		LCD_display_image(image, image_size_in_pixels, (const lcd_context_t *)&g_lcd_context);

	}

	if(remainder_10s > 0)
	{
		uint32_t  count = remainder_10s / height_step_size;

		uint32_t offset = height_step_size * step;
		for(i = 1; i <= count; i++ )
		{
			g_lcd_context.area.x1.whole = 0;
			g_lcd_context.area.y1.whole = (PORTRAIT_ACTIVE_HEIGHT - (offset + (i * height_step_size )))-1;
			g_lcd_context.area.x2.whole = PORTRAIT_ACTIVE_WIDTH - 1;
			g_lcd_context.area.y2.whole = PORTRAIT_ACTIVE_HEIGHT - 1;
			image_size_in_pixels = (offset +  (i * height_step_size)) * img_w;

			LCD_display_image(image, image_size_in_pixels, (const lcd_context_t *)&g_lcd_context);
		}
	}
	return;
}

void LCD_display_portrait_image_in_landscape_mode(const uint8_t *image, const uint16_t img_w, const uint16_t img_h )
{

	image += 14400;  // trim the white area in the portrait image. 30 lines * 240 pixels * 2 bytes each.

	uint16_t img_offset_width = (LANDSCAPE_ACTIVE_WIDTH-img_w)/2;

	g_lcd_context.area.x1.whole = img_offset_width;
	g_lcd_context.area.y1.whole = 0;
	g_lcd_context.area.x2.whole = img_offset_width + img_w -1;
	g_lcd_context.area.y2.whole = (img_h > LANDSCAPE_ACTIVE_HEIGHT) ?  (LANDSCAPE_ACTIVE_HEIGHT-1) : (img_h -1);

	size_t size_in_pixels = (img_h  > LANDSCAPE_ACTIVE_HEIGHT) ? (LANDSCAPE_ACTIVE_HEIGHT * img_w ) :(img_w * img_h ) ;

	g_lcd_context.ori.orientation = LANDSCAPE;
	LCD_set_orientation(&g_lcd_context);

	LCD_display_image(image, size_in_pixels, (const lcd_context_t *)&g_lcd_context);
}


void LCD_display_portrait_image_whole_screen(const uint8_t *image,  size_t size_in_bytes)
{
	g_lcd_context.area.x1.whole = 0;
	g_lcd_context.area.y1.whole = 0;
	g_lcd_context.area.x2.whole = PORTRAIT_ACTIVE_WIDTH - 1;
	g_lcd_context.area.y2.whole = PORTRAIT_ACTIVE_HEIGHT - 1;

	LCD_display_image(image, size_in_bytes/2, (const lcd_context_t *)&g_lcd_context);
}
